### PR TITLE
Create buzztrax.desktop

### PR DESCRIPTION
**Pull request by trebmuh**
which is used to get a menu item (freedesktop standard).

Hope that helps.

### CODE REVIEW

**Comment by trebmuh** [comment]
I don't know why travis complains. It sounds like an error to me.

**Comment by trebmuh** [comment]
@ensonic : ping?

**Comment by ensonic** [comment]
The application is already installing a desktop file:
./src/ui/edit/buzztrax-edit.desktop
This is generated from 
https://github.com/Buzztrax/buzztrax/blob/master/src/ui/edit/buzztrax-edit.desktop.in

Is this not generated for you?

**Comment by trebmuh** [comment]
That is totally correct. I can't think of why I didn't find it back in August.
All is fine, then closing here.
Thank you @ensonic

**Pull request closed without merging**
