### PR TITLE
Give 'version' headers project-specific names

### PR DESCRIPTION
**Pull request by dlbeswick**
On my system it was clashing with the version.h belonging to alsa.
Name the header such that it less-ambiguously belongs to the buzztrax project.
Remove include where it wasn't need to reduce header dependencies.

### CODE REVIEW

**Comment by ensonic** [comment]
Which linux distro are you on and whats the full name to the alsa header file. This should still work as we reference version.h by full name. Please put the compile error on a gist and link from here.

**Comment by dlbeswick** [comment]
Right, I see this happening only when I build out-of-tree (i.e. mkdir build, cd build, ../configure)

https://gist.github.com/dlbeswick/31167cb58587d1e9b767b2099d5d1cdb

**Comment by dlbeswick** [comment]
Ubuntu 19.04

**Comment by ensonic** [comment]
I'll do a out-or-src-tree build tomorrow to reproduce. We should be able to fix it without renaming the files. Renaming the files would also be a little annoying to people that package files for distros and so on.

**Comment by ensonic** [comment]
I can reproduce this. Let me fix it.

**Comment by ensonic** [comment]
I think I've fixed this with
https://github.com/Buzztrax/buzztrax/commit/4f465206cd37d95629f5ca831d53ec545acacae2

You can do a `git clone https://github.com/Buzztrax/buzztrax.git buzztrax.test` (to clone to a new dir) and build. If it works there you should be able to close the PR and use `git rebase -i` to delete the pacthes that rename the headers.

**Comment by dlbeswick** [comment]
It works for me -- thanks! Closing.

**Pull request closed without merging**
