### PR TITLE
Set up CI

### LINKED ISSUE #126: migrate ci-setup to github-actions
We used Travic-Ci in the past (see .travis.yml in the repos). 2 Options:

1. Apply for a free open source project plan at travis
1. Go though https://docs.github.com/en/actions/migrating-to-github-actions/manually-migrating-to-github-actions/migrating-from-travis-ci-to-github-actions

### PR DESCRIPTION
**Pull request by rffontenelle**
Here's an work-in-progress CI setup for testing buzztrax. There is a lot of space for improvements, like the fact that it is currently failing.

It is triggered when pushing to master branch, opening a pull request to master, and started manually in Actions page.

I based this workflow file in [.travis.yml](https://github.com/Buzztrax/buzztrax/blob/416823e4ffb567b7ff0e21448883e938b9638479/.travis.yml) and went adding dependencies the were needed to pass configure step.

Closes #126

### CODE REVIEW

**Comment by ensonic** [comment]
> @ensonic CI runs in my fork because I added the CI file to master branch and then went testing in another branch. How about having a initial workflow file so the pull requests trigger a CI workflow run?
> 
> For instance, a `.github/workflows/build.yml` containing
> 
> ```yaml
> name: Build
> 
> on:
>   pull_request:
>     branches: 'master'
> 
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     steps:
>     - run: echo 'pass'
> ```
> 
> would be enough to trigger my tests.

Good idea. Added, you need to rebase the branch though.

**Comment by rffontenelle** [comment]
@ensonic Easy fix for a merge conflict. Now that I rebased (and force-pushed due to the first commit), can you please approve workflow to be run?

**Comment by ensonic** [comment]
It run. I'll check the build step that failed, probably because I locally don't build with:
```
	Documentation (API)             : no
	Documentation (Man)             : no
	Bindings Metadata (GIR)         : no
```

**Comment by rffontenelle** [comment]
btw, The PR has permissions for maintainers to include commit. Feel free to add some commits.

**Comment by rffontenelle** [comment]
yay, enabling docs made the build go further:

```
src/lib/core/machine.c: In function ‘bt_machine_clone’:
src/lib/core/machine.c:1489:10: error: ‘machine’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1489 |   return machine;
      |          ^~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:6443: src/lib/core/libbuzztrax_core_la-machine.lo] Error 1
```

**Comment by ensonic** [comment]
I've fixed the warning (that was a more recent change, so it's great if we have a ci to catch in in the PR review).
I'll now see what's causing the make error. I suspect that some dependency is wrong and depending to the parallelism applied it works or it doesn't.

**Comment by ensonic** [comment]
> Disabling `--enable-debug`, the build went further, but then it failed in the same `C/version.entities` . See the [workflow run](https://github.com/rffontenelle/buzztrax/actions/runs/7736037754/job/21092705755).
> 
> ```
> Making all in docs/help/bt-edit
> make[2]: *** No rule to make target 'C/version.entities', needed by 'all'.  Stop.
> make[2]: Entering directory '/home/runner/work/buzztrax/buzztrax/docs/help/bt-edit'
> make[2]: Leaving directory '/home/runner/work/buzztrax/buzztrax/docs/help/bt-edit'
> make[1]: *** [Makefile:7778: all-recursive] Error 1
> make[1]: Leaving directory '/home/runner/work/buzztrax/buzztrax'
> make: *** [Makefile:3262: all] Error 2
> ```
@dlbeswick you left a note in https://github.com/Buzztrax/buzztrax/blob/master/docs/help/bt-edit/Makefile.am#L45 on the move, but it seems to also have weird side effects.

**Comment by ensonic** [comment]
I'll give up for today. Might try to revert https://github.com/Buzztrax/buzztrax/commit/e97b1c03f7c1f8bedb6556c977fcd255594854d7 but then the out-of-srcdir build might be broken again.

**Comment by rffontenelle** [comment]
Now, the CI-related question is: what flags do we want enabled? Simply enable-debug seems to me as failing too early because of warnings, hence hiding actual errors.

We could e.g. add more than one build statement, to build more relaxed flags (to see if it pass) and then debug enabled.

Anyway, there is room to improve in this CI.

Also, should we consider (in another PR, maybe) a workflow for pulling translations from translationproject.org ? It could run scheduled and, in the end, create a pull request to be manually merged when wanted. Other workflow could be to manually (workflow_dispatch or on a new git tag) push new version and strings to translationproject.org. Let me know what you think

**Comment by rffontenelle** [comment]
Artifacts are now being stored after rerunning tests from `make check` :rocket:

**Comment by ensonic** [comment]
I've cherry-picked the doc build fix to master and rebased. I think we can merge this. I'll spend some time in the next days to see if I can fix the tests that are broken at HEAD (or temporarily deactivate them).
@rffontenelle, any preference on squash the commits vs. keeping all individual ones?

**Comment by rffontenelle** [comment]
Not squash might make the git history a noisy, but I'll leave it to you to decide.

**Comment by ensonic** [comment]
Thanks a lot!

**Pull request merged**
